apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: welcome-pipeline-run
spec:
  params:
    - name: imageTag
      value: "2.0.0"
  resources:
    - name: appSource
      resourceRef:
        name: welcome-service-git-source
  pipelineRef:
    name: welcome-deployment
